### ISSUE TITLE
Unable to start Sinatra server via ruby app.rb

### ISSUE THREAD

**Issue by gj** [learn-co-curriculum/what-is-sinatra#10]
When students run `rackup` or `shotgun` in the IDE to start a Sinatra server, the command is properly intercepted and routed on the backend. However, when students run `ruby app.rb` it isn't, and it results in the following failure:
```
[02:01:30] (master) sinatra-hello-world-basics-v-000                                            
// ♥ ruby app.rb                                                                                
== Sinatra (v1.4.7) has taken the stage on 4567 for development with backup from Thin           
Thin web server (v1.7.0 codename Dunder Mifflin)                                                
Maximum connections set to 1024                                                                 
Listening on localhost:4567, CTRL+C to stop                                                     
Stopping ...                                                                                    
== Sinatra has ended his set (crowd applauds)                                                   
/usr/local/rvm/gems/ruby-2.3.1/gems/eventmachine-1.2.0.1/lib/eventmachine.rb:530:in `start_tcp_server': no acceptor (port is in use or requires root privileges) (RuntimeError)                 
        from /usr/local/rvm/gems/ruby-2.3.1/gems/eventmachine-1.2.0.1/lib/eventmachine.rb:530:in `start_server'                                                                                 
        from /usr/local/rvm/gems/ruby-2.3.1/gems/thin-1.7.0/lib/thin/backends/tcp_server.rb:16:in `connect'                                                                                     
        from /usr/local/rvm/gems/ruby-2.3.1/gems/thin-1.7.0/lib/thin/backends/base.rb:63:in `block in start'                                                                                    
        from /usr/local/rvm/gems/ruby-2.3.1/gems/eventmachine-1.2.0.1/lib/eventmachine.rb:194:in `run_machine'                                                                                  
        from /usr/local/rvm/gems/ruby-2.3.1/gems/eventmachine-1.2.0.1/lib/eventmachine.rb:194:in `run'                                                                                          
        from /usr/local/rvm/gems/ruby-2.3.1/gems/thin-1.7.0/lib/thin/backends/base.rb:73:in `start'                                                                                             
        from /usr/local/rvm/gems/ruby-2.3.1/gems/thin-1.7.0/lib/thin/server.rb:162:in `start'   
        from /usr/local/rvm/gems/ruby-2.3.1/gems/rack-1.6.4/lib/rack/handler/thin.rb:19:in `run'
        from /usr/local/rvm/gems/ruby-2.3.1/gems/sinatra-1.4.7/lib/sinatra/base.rb:1506:in `start_server'                                                                                       
        from /usr/local/rvm/gems/ruby-2.3.1/gems/sinatra-1.4.7/lib/sinatra/base.rb:1444:in `run!'                                                                                               
        from /usr/local/rvm/gems/ruby-2.3.1/gems/sinatra-1.4.7/lib/sinatra/main.rb:25:in `block in <module:Sinatra>'
```
Have to either change that functionality or the README for this lesson, which instructs students to `start this web application by running ruby app.rb`.

cc: @aturkewi 

P.S.: Props to @mekowalski for (apparently) being the only student using the IDE to actually try to follow the instructions! 😆

**Comment by mekowalski** [comment]
@gj Thank you for looking into this even further! I appreciated your help yesterday and simply wanted to make sure my program was running properly.

**Comment by aturkewi** [comment]
Alright, it's all set now! Thanks for pointing this out all!

@mekowalski if you want to give this another try, take a look at the steps added in PR #11 
You should just have to add [two lines](https://github.com/learn-co-curriculum/what-is-sinatra/blob/06a3c299b5bb35dd7569b2b0a184343a696a4b8c/app.rb) to the `app.rb` file to get this working with the Learn IDE :)

**Comment by mekowalski** [comment]
Hey @aturkewi I retried this and still ran into an error.  In the readme the file `app.rb` still only contains four lines of codes.  Other students using Learn IDE won't know any better what two lines of code to uncomment, in the note section under the `app.rb` file's code.

I tried `gem install sinatra`, ran `ruby app.rb` and still received a runtime error.  I am further along in Sinatra therefore I believe the program is working properly for now.  I will reach out if I run into anything else.

**Comment by aturkewi** [comment]
Hey @mekowalski 
Because you're fork of the lab is pre-fix, you won't have the updated lines in your copy. What you'll have to do is manually copy in the two lines. Take a look at this link https://github.com/learn-co-curriculum/what-is-sinatra/blob/06a3c299b5bb35dd7569b2b0a184343a696a4b8c/app.rb to see where to put them in your copy. If you're still having trouble, feel free to message me on Slack or on learn.co/lobby
