### ISSUE TITLE
ENV["HOST_PORT"] returns nil

### ISSUE THREAD

**Issue by NStephenson** [learn-co-curriculum/what-is-sinatra#14]
This lesson wasn't able to load up the sinatra server when a student did `ruby app.rb`. On as screen share I discovered that `ENV["HOST_PORT"]` was returning `nil`, most likely because this key was removed from or changed in ENV hash. I was able to get Sinatra to work by manually passing in an port number but this could potentially cause more issue for students in the future.

@aturkewi

**Comment by aturkewi** [comment]
Fixed in PR #15
