### ISSUE TITLE
different terminal output for ruby 2.6.1

### ISSUE THREAD

**Issue by joanrig** [learn-co-curriculum/what-is-sinatra#19]
output looks like this

`[2019-03-31 14:45:45] INFO  WEBrick 1.4.2
[2019-03-31 14:45:45] INFO  ruby 2.6.1 (2019-01-30) [x86_64-darwin18]
[2019-03-31 14:45:45] INFO  WEBrick::HTTPServer#start: pid=69165 port=9292
^C[2019-03-31 14:45:55] INFO  going to shutdown ...
[2019-03-31 14:45:55] INFO  WEBrick::HTTPServer#start done.`

not 
`$ rackup app.rb
Puma starting in single mode...
* Version 3.10.0 (ruby 2.3.0-p0), codename: Russell's Teapot
* Min threads: 0, max threads: 16
* Environment: development
* Listening on tcp://localhost:9292
Use Ctrl-C to stop` 
and not
`
* Listening on tcp://localhost:9292
Use Ctrl-C to stop
^C- Gracefully stopping, waiting for requests to finish
=== puma shutdown: 2017-11-15 09:41:19 -0500 ===
- Goodbye!
[00:01:11] (wip-lesson) what-is-sinatra
$`

**Comment by joanrig** [comment]
to clarify, when you hit control+C, you get this: `WEBrick::HTTPServer#start done.` not this `^C- Gracefully stopping, waiting for requests to finish
=== puma shutdown: 2017-11-15 09:41:19 -0500 ===
Goodbye!` 

btw spoke with AAQ tech coach Diego Y. and he believes what i'm seeing is the result of me running a different version of ruby.

**Comment by drakeltheryuujin** [comment]
Hi @joanrig,

Thank you for spotting this issue and providing feedback. This feedback checks out, and have updated the materials and believe your issue to have been resolved.

We apologize for any confusion you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
